exports.seed = async function (knex) {
  await knex("smart_trash").del();
  await knex("smart_trash").insert([
    {
      trashTypeID: 2,
      longitude: 23.85437,
      latitude: 61.45721,
      contactUserID: 2,
      optional_description: "Roskis on lähellä ovea",
      building: 1,
      height: 120,
      alarm_treshold: 80,
    },
    {
      trashTypeID: 2,
      longitude: 23.85459,
      latitude: 61.45725,
      contactUserID: 2,
      optional_description: "Roskis on lähellä ovea",
      building: 1,
      height: 120,
      alarm_treshold: 10,
    },
    {
      trashTypeID: 2,
      longitude: 23.85459,
      latitude: 61.45725,
      contactUserID: 2,
      optional_description: "Roskis on lähellä ovea",
      building: 1,
      height: 120,
      alarm_treshold: 20,
    },
    {
      trashTypeID: 2,
      longitude: 23.85459,
      latitude: 61.45725,
      contactUserID: 2,
      optional_description: "Roskis on lähellä ovea",
      building: 1,
      height: 120,
      alarm_treshold: 30,
    },
    {
      trashTypeID: 2,
      longitude: 23.85459,
      latitude: 61.45725,
      contactUserID: 2,
      optional_description: "Roskis on lähellä ovea",
      building: 1,
      height: 120,
      alarm_treshold: 40,
    },
    {
      trashTypeID: 2,
      longitude: 23.85459,
      latitude: 61.45725,
      contactUserID: 2,
      optional_description: "Roskis on lähellä ovea",
      building: 1,
      height: 120,
      alarm_treshold: 50,
    },
    {
      trashTypeID: 2,
      longitude: 23.85459,
      latitude: 61.45725,
      contactUserID: 2,
      optional_description: "Roskis on lähellä ovea",
      building: 1,
      height: 120,
      alarm_treshold: 60,
    },
    {
      trashTypeID: 1,
      longitude: 23.85437,
      latitude: 61.45721,
      contactUserID: 2,
      optional_description: "Roskis on lähellä ovea",
      building: 2,
      height: 120,
      alarm_treshold: 80,
    },
    {
      trashTypeID: 2,
      longitude: 23.85459,
      latitude: 61.45725,
      contactUserID: 2,
      optional_description: "Roskis on lähellä ovea",
      building: 2,
      height: 120,
      alarm_treshold: 10,
    },
    {
      trashTypeID: 1,
      longitude: 23.854242,
      latitude: 61.457194,
      contactUserID: 3,
      optional_description: "Roskis on lähellä ovea",
      building: 1,
      height: 120,
      alarm_treshold: 90,
    },
    {
      trashTypeID: 2,
      longitude: 23.854242,
      latitude: 61.457194,
      contactUserID: 3,
      optional_description: "Roskis on lähellä ovea",
      building: 2,
      height: 120,
      alarm_treshold: 60,
    },
  ]);
};
