PUT http://localhost:3001/notifications/2/mark-read HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjIsInVzZXJfdHlwZSI6MiwiZW1haWwiOiJtYWludEBleGFtcGxlLmNvbSIsInBob25lIjoiOTg3NjU0MzIxMCIsImZ1bGxuYW1lIjoiTWFpbnRlbmFuY2UgR3V5IiwiY2FtcHVzSUQiOjEsImlhdCI6MTc2MjE3MjIwOCwiZXhwIjoxNzYyNzc3MDA4fQ.F3TRsyeacn0aAnbSNSNJD8B2Rpyr5j_k9ACwXprIZ4c

{
    "notificationIds": [6,7],
    "read": "true"
}